### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by javiermortiz** [nkuek/discordance#1]
Looks good! Adding members to a server should be part of the "Servers" feature. Also under "Live chat", I saw reactions to messages. In my opinion that is a feature on itself. Maybe save it as a bonus?

**Comment by nkuek** [comment]
We were thinking about doing that as bonus, but we are still unsure if we wanted to have emoji reactions to messages like in discord or just a simple like function. We felt like the like function would be simple enough to implement, but yes I do think that the reaction function would be more complicated and could probably be bonus.
